export const monetaryItemSeedData = [
  {
    name: "Rent",
    value: 1000,
    date: new Date("2021-01-01").toISOString(),
    repeat: true,
    repeatPeriod: "monthly",
    repeatEndDate: new Date("2021-12-31").toISOString(),
    type: "expense",
  },
  {
    name: "Groceries",
    value: 200,
    date: new Date("2021-01-01").toISOString(),
    repeat: true,
    repeatPeriod: "weekly",
    repeatEndDate: new Date("2021-12-31").toISOString(),
    type: "expense",
  },
  {
    name: "Salary",
    value: 2000,
    date: new Date("2021-01-01").toISOString(),
    repeat: true,
    repeatPeriod: "monthly",
    repeatEndDate: new Date("2021-12-31").toISOString(),
    type: "income",
  },
  {
    name: "Bonus",
    value: 500,
    date: new Date("2021-01-01").toISOString(),
    repeat: false,
    repeatEndDate: new Date("2021-12-31").toISOString(),
    type: "income",
  },
];
